### ISSUE TITLE
Bring back smoke tests !

### ISSUE THREAD

**Issue by faxm0dem** [ccin2p3/puppet-patterndb#22]
For reference here is what we do in gitlab-ci:
```
smoke syslog-ng puppet 5:
  stage: smoke
  image: ruby:2.4.5
  variables:
    PUPPET_GEM_VERSION: "~> 5"
  script:
  - apt-get update
  - apt-get install syslog-ng -y
  - syslog-ng --version
  - bundle install --without system_tests --path vendor/bundle
  - bundle exec puppet --version
  - bundle exec puppet module build
  - bundle exec puppet module install pkg/*.tar.gz
  - bundle exec ./smoke/test
smoke syslog-ng latest:
  stage: smoke
  allow_failure: true
  image:
    name: balabit/syslog-ng:latest
    entrypoint:
    - ''
  variables:
    PUPPET_GEM_VERSION: "~> 5"
  before_script: []
  script:
  - apt-get update
  - apt-get install ruby bundler -y
  - 'bundle install --without system_tests --path vendor/bundle || :'
  - bundle exec puppet --version
  - bundle exec puppet module build
  - bundle exec puppet module install pkg/*.tar.gz
  - bundle exec ./smoke/test

```
